/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.forme;

import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Bane
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        super("Početna strana");
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelaUlogovaniKorisnik = new javax.swing.JLabel();
        btnKraj = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuGost = new javax.swing.JMenu();
        jmiDodajGosta = new javax.swing.JMenuItem();
        jmiPretraziGoste = new javax.swing.JMenuItem();
        jMenuSoba = new javax.swing.JMenu();
        jmiDodajSobu = new javax.swing.JMenuItem();
        jmiPretraziSobe = new javax.swing.JMenuItem();
        jMenuRezervacija = new javax.swing.JMenu();
        jmiDodajRezervaciju = new javax.swing.JMenuItem();
        jmiPretraziRezervaciju = new javax.swing.JMenuItem();
        jMenuOpis = new javax.swing.JMenu();
        jmiSoftver = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnKraj.setText("Kraj rada");

        jMenuGost.setText("Gost");

        jmiDodajGosta.setText("Dodaj gosta");
        jMenuGost.add(jmiDodajGosta);

        jmiPretraziGoste.setText("Pretraži gosta po imenu i prezimenu");
        jMenuGost.add(jmiPretraziGoste);

        jMenuBar1.add(jMenuGost);

        jMenuSoba.setText("Soba");

        jmiDodajSobu.setText("Dodaj sobu");
        jMenuSoba.add(jmiDodajSobu);

        jmiPretraziSobe.setText("Pretraži sobe po spratu");
        jMenuSoba.add(jmiPretraziSobe);

        jMenuBar1.add(jMenuSoba);

        jMenuRezervacija.setText("Rezervacija");

        jmiDodajRezervaciju.setText("Dodaj rezervaciju");
        jMenuRezervacija.add(jmiDodajRezervaciju);

        jmiPretraziRezervaciju.setText("Pretraži rezervaciju po datumu početka");
        jMenuRezervacija.add(jmiPretraziRezervaciju);

        jMenuBar1.add(jMenuRezervacija);

        jMenuOpis.setText("Opis");

        jmiSoftver.setText("O softveru");
        jMenuOpis.add(jmiSoftver);

        jMenuBar1.add(jMenuOpis);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelaUlogovaniKorisnik)
                .addContainerGap(394, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKraj)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelaUlogovaniKorisnik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                .addComponent(btnKraj)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKraj;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuGost;
    private javax.swing.JMenu jMenuOpis;
    private javax.swing.JMenu jMenuRezervacija;
    private javax.swing.JMenu jMenuSoba;
    private javax.swing.JMenuItem jmiDodajGosta;
    private javax.swing.JMenuItem jmiDodajRezervaciju;
    private javax.swing.JMenuItem jmiDodajSobu;
    private javax.swing.JMenuItem jmiPretraziGoste;
    private javax.swing.JMenuItem jmiPretraziRezervaciju;
    private javax.swing.JMenuItem jmiPretraziSobe;
    private javax.swing.JMenuItem jmiSoftver;
    private javax.swing.JLabel labelaUlogovaniKorisnik;
    // End of variables declaration//GEN-END:variables

    public void jmiDodajGostaAddActionListener(ActionListener actionListener) {
        jmiDodajGosta.addActionListener(actionListener);
    }

    public void jmiPretraziGosteAddActionListener(ActionListener actionListener) {
        jmiPretraziGoste.addActionListener(actionListener);
    }

    public void jmiDodajSobuAddActionListener(ActionListener actionListener) {
        jmiDodajSobu.addActionListener(actionListener);
    }

    public void jmiPretraziSobeAddActionListener(ActionListener actionListener) {
        jmiPretraziSobe.addActionListener(actionListener);
    }

    public void jmiDodajRezervacijuAddActionListener(ActionListener actionListener) {
        jmiDodajRezervaciju.addActionListener(actionListener);
    }

    public void jmiPretraziRezervacijuAddActionListener(ActionListener actionListener) {
        jmiPretraziRezervaciju.addActionListener(actionListener);
    }

    public void jmiSoftverAddActionListener(ActionListener actionListener) {
        jmiSoftver.addActionListener(actionListener);
    }
    
    public void addKrajBtnAddActionListener(ActionListener actionListener) {
        btnKraj.addActionListener(actionListener);
    }
    
    public JLabel getLabelaUlogovaniKorisnik() {
        return labelaUlogovaniKorisnik;
    }

}
